### ISSUE TITLE
Missing licence file

### ISSUE THREAD

**Issue by JGrossholtz** [All4Gis/Load-QSS#5]
Your Qt themes are great and I would like to use and modify them. But unfortunately it is not clear if we are allowed to do so and in what conditions.

Could you please add a Licence to make things clear ?

Thanks a lot !

**Comment by All4Gis** [comment]
Of course,Feel free to use them. FreeCad styles come from here https://github.com/FreeCAD/FreeCAD/tree/bdf4bfe3033b304b0d0053515eb0a54519ee76c9/src/Gui/Stylesheets ,there's more.

**Comment by JGrossholtz** [comment]
Thanks for your answer !

Julien
