### ISSUE TITLE
qlineargradient in toolbar not working

### ISSUE THREAD

**Issue by Brigggi** [All4Gis/Load-QSS#6]
I want to have a qlineargradient for the QGIS toolbar. 

But if I load a QSS file with the following code, the top toolbar is getting black while the bars below Browser and Layer get the desired gradient.

```
QToolBar {
    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #0077B6 stop:1 #80CDEC);
}
```

![QSS_test_colors](https://user-images.githubusercontent.com/59602238/161936554-ec2d436e-d72c-44fa-a9f4-4cd5c2e252bd.png)

Is this a bug or am I doing something wrong?

Using a simple color, all bars work fine:
```
QToolBar {
    background-color: #80CDEC;
}
```
![QSS_color_test2](https://user-images.githubusercontent.com/59602238/161944905-31e743fb-3f64-432c-91bc-f191fb979e52.png)

**Comment by All4Gis** [comment]
funny, if you just change only the background color it doesn't work but if you add some change the border as well it works too. Why? I honestly don't know

```
QToolBar {
    border: 1px transparent #393838;
    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #0077B6 stop:1 #80CDEC);
}
```

**Comment by Brigggi** [comment]
Thank you, that solved my problem! :)
